/*------
STRUCTURE

1 - TYPE & TABLE ARTISTE

2 - TYPE ABONNEMENT

3 - TYPE ABONNE

4 - TYPE SOCIETE / PUBLIC / PARTICULIER

5 - TABLE SOCIETE / PUBLIC / PARTICULIER

6 - TYPE & TABLE EMPRUNT

------*/

/*----------------------------------------
1 - TYPE & TABLE ARTISTE
-----------------------------------------*/

CREATE OR REPLACE TYPE ARTISTE_TYPE AS OBJECT
(
  REF_ARTISTE NUMBER(6),
  NOM         VARCHAR(20),
  PRENOM      VARCHAR(20)
);

CREATE TABLE ARTISTE OF ARTISTE_TYPE
(
  PRIMARY KEY (REF_ARTISTE)
);

/*----------------------------------------
2 - TYPE ABONNEMENT
-----------------------------------------*/


CREATE TABLE TYPE_ABONNEMENT
(
  ID             NUMBER,
  TYPE_ABONNE    VARCHAR(50),
  MONTANT_ANNUEL NUMBER(4, 2),

  PRIMARY KEY (ID)
);

-- TODO OPTIMISATION TYPE_ABONNEMENT

CREATE OR REPLACE TYPE ABONNEMENT_TYPE AS OBJECT
(
  REF_ABONNE               NUMBER,
  DATE_DEBUT               DATE,
  DATE_PROCHAIN_ABONNEMENT DATE,
  EST_REGLE                BOOLEAN,
  TYPE_ABONNEMENT          NUMBER
);

/*----------------------------------------
3 - TYPE ABONNE
-----------------------------------------*/

CREATE OR REPLACE TYPE ABONNE_TYPE AS OBJECT
(
  REF_ABONNE NUMBER,
  ADRESSE    VARCHAR(255),
  EMAIL      VARCHAR(240),
  TELEPHONE  VARCHAR(13),
  ABONNEMENT ABONNEMENT_TYPE,
  HISTORIQUE HISTORIQUE_TYPE
) NOT FINAL NOT INSTANTIABLE;

/*----------------------------------------
4 - TYPE SOCIETE / PUBLIC / PARTICULIER
-----------------------------------------*/

CREATE OR REPLACE TYPE SOCIETE_TYPE UNDER ABONNE_TYPE
(
  NOM_SOCIETE VARCHAR(255)
);

CREATE OR REPLACE TYPE PARTICULIER_TYPE UNDER ABONNE_TYPE
(
  NOM    VARCHAR(255),
  PRENOM VARCHAR(255)
);

CREATE OR REPLACE TYPE ETABLISSEMENT_PUBLIC_TYPE UNDER ABONNE_TYPE
(
  NOM_ETABLISSEMENT VARCHAR(255)
);

/*----------------------------------------
5 - TABLE SOCIETE / PUBLIC / PARTICULIER
-----------------------------------------*/

CREATE TABLE SOCIETE OF SOCIETE_TYPE
(
  PRIMARY KEY (REF_ABONNE)
);

CREATE TABLE PARTICULIER OF PARTICULIER_TYPE
(
  PRIMARY KEY (REF_ABONNE)
);

CREATE TABLE ETABLISSEMENT_PUBLIC OF ETABLISSEMENT_PUBLIC_TYPE
(
  PRIMARY KEY (REF_ABONNE)
);

/*----------------------------------------
6 - TYPE & TABLE EMPRUNT
-----------------------------------------*/

CREATE OR REPLACE TYPE EMPRUNT_TYPE AS OBJECT
(
  REF_EMPRUNT  NUMBER,
  DATE_EMPRUNT DATE,
  DATE_RETOUR  DATE,
  REF_OEUVRE   NUMBER,
  REF_ABONNE   NUMBER
);

CREATE TABLE EMPRUNT OF EMPRUNT_TYPE
(
  PRIMARY KEY (REF_EMPRUNT)
);

/*----------------------------------------
7 - TYPE CRITIQUE
-----------------------------------------*/

CREATE OR REPLACE TYPE CRITIQUE_TYPE AS OBJECT
(
  AUTEUR   VARCHAR(255),
  CRITIQUE VARCHAR(1024)
);

CREATE OR REPLACE TYPE CRITIQUE_LIST AS TABLE OF CRITIQUE_TYPE;

CREATE TYPE HISTORIQUE_TYPE AS TABLE OF EMPRUNT_TYPE;

/*----------------------------------------
8 - TYPE & TABLE OEUVRE
-----------------------------------------*/

CREATE OR REPLACE TYPE OEUVRE_TYPE AS OBJECT
(
  REF_OEUVRE  NUMBER,
  TITRE       VARCHAR(255),
  PRIX        NUMBER(4, 2),
  SUPPORT     ENUM('1', '2'),
  GENRE       ENUM('1', '2'),
  DESCRIPTION varchar(1024),
  CRITIQUE    CRITIQUE_LIST
);

CREATE TABLE OEUVRE OF OEUVRE_TYPE
(
  PRIMARY KEY (REF_OEUVRE)
);

/*----------------------------------------
9 - TABLE OEUVRE_ARTISTE

Permet la recherche rapide d'association oeuvre / artiste

-----------------------------------------*/

CREATE TABLE OEUVRE_ARTISTE
(
  REF_OEUVRE  NUMBER,
  REF_ARTISTE NUMBER,

  CONSTRAINT FK_OEUVRE FOREIGN KEY (REF_OEUVRE) REFERENCES OEUVRE (REF_OEUVRE),
  CONSTRAINT FK_ARTISTE FOREIGN KEY (REF_ARTISTE) REFERENCES ARTISTE (REF_ARTISTE)
)
